global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cd-cli-exporter"
    static_configs:
      - targets: ["cd-cli-exporter:9400"]

  - job_name: "cd-restapi-exporter"
    static_configs:
      - targets: ["cd-restapi-exporter:9401"]

  - job_name: "cd-java-exporter"
    static_configs:
      - targets: ["cd-java-exporter:9402"]
